version: '3.8'

services:
  finance-dashboard:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ../data:/app/data
      - ../config:/app/config
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    
  # Optional: PostgreSQL for production
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: finance_dashboard
      POSTGRES_USER: finance_user
      POSTGRES_PASSWORD: finance_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data: