expense_prediction:
  arima:
    order: [1, 1, 1]
    seasonal_order: [1, 1, 1, 12]
  
  ml_model:
    model_type: "random_forest"
    n_estimators: 100
    max_depth: 10
    random_state: 42
    
  features:
    lag_periods: [1, 7, 14, 30]
    rolling_windows: [7, 30]
    
category_classification:
  vectorizer:
    max_features: 1000
    stop_words: "english"
    ngram_range: [1, 2]
  
  classifier:
    n_estimators: 100
    max_depth: 15
    random_state: 42

anomaly_detection:
  isolation_forest:
    contamination: 0.1
    random_state: 42
    n_estimators: 100
  
  statistical:
    zscore_threshold: 3
    iqr_multiplier: 1.5
